Website/Website/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home,name='home'),
    url(r'^home/', include('homepage.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^special/', views.special, name='special'),
    url(r'^europe/', views.calculateprice, name='calculateprice'),
    url(r'^user_logout/$', views.user_logout, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/homepage/urls.py
from django.conf.urls import url
from homepage import views

# SET THE NAMESPACE!
app_name = 'homepage'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^profile/$',views.profile, name='profile'),
    # url(r'^profile/profile_pics$', views.profile, name='profile'),
    # path('login/',login,views.user_login),
    url(r'^europe/$', views.europe, name='europe'),
    # url(r'^$', views.europe, name='europe'),
    url(r'^sample/$', views.sample, name = 'sample'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^blog/index/$', views.index, name='index'),
    url(r'^calculateprice/$', views.calculateprice, name='calculateprice'),
    # url(r'^user_id/$', )
    url(r'^blog/index/first/$', views.first, name='first'),
    url(r'^blog/index/second/$', views.second, name='second'),
    url(r'^blog/index/third/$', views.third, name='third'),
    url(r'^blog/index/fourth/$', views.fourth, name='fourth'),
    url(r'^blog/index/fifth/$', views.fifth, name='fifth'),
    url(r'^blog/index/sixth/$', views.sixth, name='sixth'),
]

Website/homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    # user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    # user = models.OneToOneField(User, on_delete=models.PROTECT)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)

    # user_id = models.CharField(on_delete=models.DO_NOTHING)


    # Add any additional attributes you want
    phone_number = models.CharField(max_length=10, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    # profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
                                                                            

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfileInfo.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    #instance.profile.username = User.objects.get('username')
    instance.userprofileinfo.save()


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class CalculatePrice(models.Model):

    # user = models.OneToOneField(User, on_delete=models.DO_NOTHING, default='')

    departure_city = models.CharField(max_length=50, default='')
    adult = models.IntegerField(default=0)
    children = models.IntegerField(default=0)
    date_of_travel = models.DateField(max_length=10, default='')

    # def __str__(self):
    #     # Built-in attribute of django.contrib.auth.models.User !
    #     return self.departure_city

Website/homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo
from .models import CalculatePrice


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('phone_number', 'first_name', 'last_name')


class CalculatePricePack(forms.ModelForm):

    class Meta:
        model = CalculatePrice
        fields = ('departure_city', 'adult', 'children', 'date_of_travel')

Website/homepage/views.py
from django.shortcuts import render,redirect
from homepage.forms import UserForm, UserProfileInfoForm, CalculatePricePack
from django.contrib.auth.models import User


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def home(request):
    return render(request, 'homepage/home.html')

@login_required
def special(request):
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('home'))


# def register(request):
#     if request.method =='POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/homepage')
#     else:
#         form = UserCreationForm()
#         args = {'form': form}
#         return render(request, 'homepage/registration.html', args)
def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user=user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors, profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'homepage/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('home'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'homepage/login.html', {})


def calculateprice(request):
    if request.method == 'POST':
        form = CalculatePricePack(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return redirect('home')
        else:
            print(form.errors)
    form = CalculatePricePack()
    return render(request, 'homepage/sample.html', {'form' : form})


def europe(request):
    return render(request, 'homepage/europe.html', {})


def profile(request):

    return render(request, 'homepage/profile.html', {'user': request.user})


def sample(request):

    return render(request, 'homepage/sample.html', {})



def aboutus(request):
    return render(request, 'homepage/aboutus.html', {})


def index(request):
    return render(request, 'homepage/blog/index.html', {})


def first(request):
    return render(request, 'homepage/blog/first.html', {})


def second(request):
    return render(request, 'homepage/blog/second.html', {})


def third(request):
    return render(request, 'homepage/blog/third.html', {})


def fourth(request):
    return render(request, 'homepage/blog/fourth.html', {})


def fifth(request):
    return render(request, 'homepage/blog/fifth.html', {})


def sixth(request):
    return render(request, 'homepage/blog/sixth.html', {})

Website/homepage/templates/homepage/aboutus.html
{% extends 'homepage/home.html' %}
{% load staticfiles %}
{% block body_block %}



<div class="container">
  <div class="jumbotron">
    <h1>About Us</h1>
<p></p>
  <p>Ever wished that there were an escape button on the keyboard of life? Well, since there isn’t , we are there for you. The universal truth is that every person in this universe needs a break at some point - A break from the mundane routines, surroundings, work and one’s entire surroundings. And what better break could be there than a well-planned HOLIDAY! A Holiday that would truly rejuvenate and refresh you.

Our aim is not merely to render a holiday tour, but also provide a bouquet of services weaved to perfection according to your needs. We believe that bringing people and places together is a noble affair. Moments which people spend with their loved ones are truly magical and blessed, and holidays are both an excuse and an opportunity to get this blessing. And so we strive to gift you a holistic experience enriched with refreshing, relaxing and rejuvenating moments that you would cherish for eternity.

Nature is inimitable - it is beyond our match! However, we certainly endeavour to take you close to nature where every destination is like an unread poetry and the pleasure lies in reading it! We not only present such infinite books, but also guide you in the right way to decipher them.</p>
</div>
</div>

{% endblock %}

Website/homepage/templates/homepage/europe.html
{% extends 'homepage/home.html' %}
{% block body_block %}


<div id="europecar" class="container">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="https://resources.thomascook.in/images/holidays/PKG000011/photos/europe_shutterstock_124543114.jpg" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>LA is always so much fun!</p>
        </div>
      </div>

      <div class="item">
        <img src="https://resources.thomascook.in/images/holidays/PKG000041/photos/London_Eye_London_UK.jpg" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago!</p>
        </div>
      </div>

        <div class="item">
        <img src="https://resources.thomascook.in/images/holidays/PKG000034/photos/Parisian-Highlights_3.jpg" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>
      </div>

    </div>
 <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<!--information-->

  <div class="tab">

  <button class="tablinks" onclick="openCity(event, 'Overview')">Overview</button>
  <button class="tablinks" onclick="openCity(event, 'Itinerary')">Itinerary</button>
</div>

<div id="Calprice" class="tabcontent">

  <div class="jumbotron">
  <p></p>


       <!--<h3>THANKS YOU FOR Calculating shit</h3>-->



  </div>
</div>

<div id="Overview" class="tabcontent">
  <h3>Overview</h3>
  <br>
  <h4 style="color: #00007e">Flight Details</h4>
  <p>Return Economy Class Airfare Included</p>
  <br>
<h4 style="color: #00007e">  Accommodation</h4>
  <p>Overnight stay at the Hotels</p>
  <br>
<h4 style="color: #00007e">Meals</h4>
<ol>
 <li> Daily basic continental buffet breakfast.(Breakfast includes bread, butter, jam, cereals, fruit juice, milk, tea and coffee)</li>

  <li>Packed lunches, if applicable, will be Jain or vegetarian</li>

  <li>Indian Jain, Vegetarian, Non-Vegetarian dinners</li>
  </ol>
</div>

<div id="Itinerary" class="tabcontent">
  <h3>Itinerary</h3>
  <p>Tokyo is the capital of Japan.</p>
</div>
<a href="{% url 'homepage:calculateprice' %}"><h1>BOOK NOW</h1></a>
  {% endblock %}

</div>

Website/homepage/templates/homepage/login.html
{% extends 'homepage/home.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'homepage:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Website/homepage/templates/homepage/profile.html
{% extends 'homepage/home.html' %}
{% block body_block %}
<h1>PROFILE</h1>
{% csrf_token %}
<p><h3>FIRST NAME : {{ user.first_name }}</h3></p>
<p><h3>LAST NAME : {{ user.last_name }}</h3></p>
<p><h3>EMAIL ID : {{ user.email }}</h3></p>
<p><h3>PHONE NUMBER : {{ user.userprofileinfo.phone_number }}</h3></p>
<p><h3>USERNAME : {{ user }}</h3></p>
<!--<img src="{{ user.userprofileinfo.profile_pic }}"  class="img-responsive" width="240" height="200">-->


       <h2>BOOKING DETAILS</h2>


        <p><h3>DEPARTURE CITY : {{ user.calculateprice.departure_city }}</h3></p>





{% endblock %}

Website/homepage/templates/homepage/registration.html
{% extends "homepage/home.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}

       <h1>THANKS YOU FOR REGISTERING</h1>
      {% else %}

        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

Website/homepage/templates/homepage/sample.html
{% extends 'homepage/home.html' %}
{% block body_block %}
{% if booked %}

       <h1>THANKS YOU FOR BOOKING</h1>
      {% else %}

        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
            {{ form.as_p }}
    <input type="submit" name="" value="SUBMIT">
        </form>


      {% endif %}

{% endblock %}