Website/Website/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home,name='home'),
    url(r'^home/', include('homepage.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^special/', views.special, name='special'),
    url(r'^europe/', views.calculateprice, name='calculateprice'),
    url(r'^user_logout/$', views.user_logout, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/homepage/urls.py
from django.conf.urls import url
from homepage import views

# SET THE NAMESPACE!
app_name = 'homepage'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^profile/$',views.profile, name='profile'),
    # url(r'^profile/profile_pics$', views.profile, name='profile'),
    # path('login/',login,views.user_login),
    url(r'^europe/$', views.europe, name='europe'),
    # url(r'^$', views.europe, name='europe'),
    url(r'^sample/$', views.sample, name = 'sample'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^blog/index/$', views.index, name='index'),
    url(r'^calculateprice/$', views.calculateprice, name='calculateprice'),
    # url(r'^user_id/$', )
    url(r'^blog/index/first/$', views.first, name='first'),
    url(r'^blog/index/second/$', views.second, name='second'),
    url(r'^blog/index/third/$', views.third, name='third'),
    url(r'^blog/index/fourth/$', views.fourth, name='fourth'),
    url(r'^blog/index/fifth/$', views.fifth, name='fifth'),
    url(r'^blog/index/sixth/$', views.sixth, name='sixth'),
]

Website/homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    # user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    # user = models.OneToOneField(User, on_delete=models.PROTECT)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)

    # user_id = models.CharField(on_delete=models.DO_NOTHING)


    # Add any additional attributes you want
    phone_number = models.CharField(max_length=10, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    # profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
                                                                            

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfileInfo.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    #instance.profile.username = User.objects.get('username')
    instance.userprofileinfo.save()


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class CalculatePrice(models.Model):

    # user = models.OneToOneField(User, on_delete=models.DO_NOTHING, default='')

    departure_city = models.CharField(max_length=50, default='')
    adult = models.IntegerField(default=0)
    children = models.IntegerField(default=0)
    date_of_travel = models.DateField(max_length=10, default='')

    # def __str__(self):
    #     # Built-in attribute of django.contrib.auth.models.User !
    #     return self.departure_city

Website/homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo
from .models import CalculatePrice


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('phone_number', 'first_name', 'last_name')


class CalculatePricePack(forms.ModelForm):

    class Meta:
        model = CalculatePrice
        fields = ('departure_city', 'adult', 'children', 'date_of_travel')

Website/homepage/views.py
from django.shortcuts import render,redirect
from homepage.forms import UserForm, UserProfileInfoForm, CalculatePricePack
from django.contrib.auth.models import User


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def home(request):
    return render(request, 'homepage/home.html')

@login_required
def special(request):
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('home'))


# def register(request):
#     if request.method =='POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/homepage')
#     else:
#         form = UserCreationForm()
#         args = {'form': form}
#         return render(request, 'homepage/registration.html', args)
def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user=user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors, profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'homepage/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('home'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'homepage/login.html', {})


def calculateprice(request):
    if request.method == 'POST':
        form = CalculatePricePack(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return redirect('home')
        else:
            print(form.errors)
    form = CalculatePricePack()
    return render(request, 'homepage/sample.html', {'form' : form})


def europe(request):
    return render(request, 'homepage/europe.html', {})


def profile(request):

    return render(request, 'homepage/profile.html', {'user': request.user})


def sample(request):

    return render(request, 'homepage/sample.html', {})



def aboutus(request):
    return render(request, 'homepage/aboutus.html', {})


def index(request):
    return render(request, 'homepage/blog/index.html', {})


def first(request):
    return render(request, 'homepage/blog/first.html', {})


def second(request):
    return render(request, 'homepage/blog/second.html', {})


def third(request):
    return render(request, 'homepage/blog/third.html', {})


def fourth(request):
    return render(request, 'homepage/blog/fourth.html', {})


def fifth(request):
    return render(request, 'homepage/blog/fifth.html', {})


def sixth(request):
    return render(request, 'homepage/blog/sixth.html', {})

Website/homepage/templates/homepage/blog/fifth.html
{% extends 'homepage/blog/index.html' %}
{% load staticfiles %}

  {% block body_block %}
<p></p>
<p><h1>Indulge Your Need For Speed In Singapore!</h1></p>
<p></p>
<img src="https://blog.thomascook.in/wp-content/uploads/2012/09/20860542330_92df58d1ef_z.jpg" alt="">
<p></p>
<footer>
<p class="post-info">Monday, September 10, 2012</p>
</footer>
<p></p>
<p>Singapore has a lot to offer for all kinds of travelers. When you plan a trip to this world class destination you can expect your vacation to be full of surprises from beautiful architecture to great food and amazing theme parks!Apart from the obvious tourist attractions, Singapore has something special to offer for sports enthusiasts! If you have a need for speed, then you should definitely plan a trip to experience 2012 Formula 1 Singapore Grand PrixSingapore is often described as the “Jewel in the Formula One crown” and this year, it looks to raise the bar with an event like none other! 24 of the world’s best drivers will race through Singapore’s Marina Bay Street Circuit at over 200 miles per hour in the world’s only F1 night race.</p>
<p></p>
<p>Apart from the race, this year the entertainment line up is packed with a star studded cast of 300 performers across 5 stages! You can expect to see performances from Katy Perry, Maroon 5 and Asia’s very own R&B king, Jay Chou.

So don’t wait any longer, plan your trip to the 2012 Formula 1 Singapore Grand Prix with us</p>
{% endblock %}

Website/homepage/templates/homepage/blog/first.html
{% extends 'homepage/blog/index.html' %}
{% load staticfiles %}

  {% block body_block %}
    <p><h1>Why Every Adventure Junkie Needs To Experience Thailand Adventures</h1></p>
<p></p>

<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/pexels-photo-357891-e1520059683510.jpeg" alt="">
<p></p>

<footer>
<p font-size="large"class="post-info">Monday, April 9, 2018</p>
</footer>

<p></p>
<p>Thailand is enormous and diverse along with the large selection of travel as well as holiday options. Thailand has held a very special place in tourist’s heart. Resorts in coast provide adventure games like bungee jumping, paragliding, and jet skiing. Thailand Adventures can give you a gala time of excitement over there.

A huge number of people out there confine themselves to the south of Thailand and then make a huge mistake of not travelling the north. But Northern Thailand is actually full of adventure along with some high mountains and terrains along with the challenging forest areas and waterfalls. If you are in Thailand, you cannot skip the Thailand Adventures where you will be a witness of bungee jumping, jet skiing and more.

There are numerous services in the countryside of Chiang Rai, Chiang Mai, Mae Hong Son and Pai that provide the trekking tours. If you are a travel buff and want to really explore the place, then experiencing all the Thailand Adventures would be a great choice for you. If you visit this place in between November to February, then trekking would be the prime option to experience.</p>


<p><h1>Here are 5 popular Thailand Adventures to experience, which you cannot say “NO” to.</h1></p>

<p><h1>1. Rock Climbing in Railay Bay</h1></p>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/rock-e1520057406738.jpg" alt="">
<p>When it comes to choose your favorite travel destination for the adventure sports, there should be the name of Thailand that you cannot skip. The place is full of culture and heritage. But apart from that, experiencing the amazing Thailand Adventures will be the cherry on the cake while visiting this place. So, amongst all of the adventure sports, Rock Climbing in Railay is one of the sought after stuff to do. Railay in Krabi Provence is the foremost sport climbing terminuses across the world. There are some routes to fit each and every individual from the beginner climber to experienced professional.

You can easily take beginner courses, multi-day lead climbing progressions, rent gear or even go off on the own and discover that numerous bolted routes. Railay Bay is really stunning along with the cliffs jutting out of the water as well as surrounding its horseshoe beaches.

Time to Visit: You can visit anytime except monsoon

Features: Bolted-Sport climbing, Overhanging routes and bouldering opportunities in shorelines, On sea stacks only reachable by boat

</p>

<p><h1>2. Elephant Trek in Khao Sok</h1> </p>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/Elephant_02-e1520057505461.jpg" alt="">
<p>When you are opting for the Thailand Adventures, you can easily include this stunning place in your list. A lovely National Park in Southern Thailand, this is less of the circus rather than the elephant treks in Chang Mai. The huge elephants seem being treated fairly and look quite healthy in Khao Sok and then to sit upon the gentle giant is a thrill. They also manage to move down the steep hills and right over rough terrain along with ease as you just hang on hoping not to take the tumble off your high perch. You can stay in one of the beautiful many bungalows or lodges in that park and spend few days by exploring the wildlife, trails, and waterfalls as well.

Time to visit: Perceptibility is best July through September.

Features: Wrecks, tropical fish, corals, killer visibility, warm water, and ample of post-dive entertainment.</p>

<p><h1>3. Meditation Course in Chang Mai</h1></p>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/meditation--e1520057804405.jpg" alt="">
<p>If you are opting for the finest Thailand Adventures, you can go for this particular adventure sports that will make you come back again and again over the place. If you manage to make this to Chang Mai, why not try something dissimilar than the trekking to see Hill Tribes or even taking any cooking course. Numerous multi-day meditation courses are presented in the area. Slow down and then relax centring yourself for rest of the journey. Learn tai chi, various kinds of the meditation and cleanse the entire body as you eat vegan dishes.

Time to visit: The perfect time to visit this Chiang Mai is between October and April.

How to reach: You can reach this place through the air service. Or else, taking a cab from the Bangkok, you can reach there.</p>

<p><h1>5.  Walking via Bridge on the River Kwai</h1></p>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/Bridge_over_River_Kwai-e1520058174910.jpg" alt="">

<p>When you are opting for the right kind of Thailand Adventures, you can easily pick up this one. This particular adventurous option will help you to come back again in this stunning place. As you know that adventure sports like climbing or river rafting provides you the excellent interest but walking over the bridge is also a fun as well. You surely would not think of this as being the thrill, but feel the ultimate rush as you just walk between railroad ties. One wrong move and you can just fall into the river. There are no wires or even cages to keep you safe and secure you only walk along the planks and create room for the others as they pass. So, this is not less courageous to take as adventure sports.

 How to reach: From Bangkok, you can avail train or even any cab. Or else, you can book the private car too.

Time to visit: January through March is one of the ideal seasons to reach.</p>
  {% endblock %}

Website/homepage/templates/homepage/blog/fourth.html
{% extends 'homepage/blog/index.html' %}
{% load staticfiles %}

  {% block body_block %}
<p>
<h1>Top 6 Restaurants For The Best Mauritius Food</h1>
</p>
<p></p>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/Kerala_Chilli_Crab-1024x656.jpg" alt="">
<p></p>
<footer>
<p class="post-info">Saturday, March 17, 2018</p>
</footer>
<p></p>

<p>FacebookTwitterGoogle+
Mauritius is a breath-taking Island nation with a beautiful landscape with panoramic views that seem like they are out of high definition movie. This quaint nation nestled near the African continent in a very popular year-round tourist destination. It has on offer an abundance of white sandy beaches, turquoise lagoons and bright, sunny days with occasional bouts of rainfall and pleasant tropical weather all year round. If you are travelling from the northern hemisphere, you can visit during summers do escape the cold, harsh winter and vis-a-vis during winters do escape from the sizzling hot weather. It’s the ideal location for a fun family vacation or a romantic getaway with your significant other. Eager to know about Mauritius food? Go on, we have an exciting read in store for you!</p>
<p></p>

<h1><b>Top 6 Restaurant for the Best Mauritius Food</b></h1>
<p></p>
<p>While summertime is best suited for a family vacation as the island is bustling with beaches and indoor and outdoor activities are abundant. Winters is best suited for a romantic holiday as there are fewer people on the island and the overall vibe is quite chill and relaxing. So, don’t waste any more time and hop onto the website to book your amazing Island holiday. Since food is such an essential part of any trip, it’s important to do some research about the local cuisine and the best restaurant to eat at, however, if you don’t have the time, relax as we have you covered. Following is a list and description of the Top 10 Restaurants for the best Mauritius Food.</p>
<p></p>

<h1>Before you dive right in, here is a summary of the 6 restaurants for best Mauritius food</h1>
<p></p>

<h1>1. Maison Eureka</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/1.-e1520949484444.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> The restaurant is located 39 km from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b>9 am to 5 pm </li>
  <li> <b>Approximate Cost for Two:</b>Each dish cost approx. INR 500-800 each.</li>
  <li> <b>Must Try:</b>Three Course Creole Meal</li>
  <li> <b>Trip Advisor Rating:</b>4/5</li>
</ul>
<p></p>

<h1>2. Le Barachois</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/2.-Le-Barachois-1-e1520949370459.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> The restaurant is located 73.1 km from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b>7pm to 10pm  </li>
  <li> <b>Approximate Cost for Two:</b>A meal for two may cost approx. INR 3000/-</li>
  <li> <b>Must Try:</b>Grilled Lobster</li>
  <li> <b>Trip Advisor Rating:</b>4.5/5</li>
</ul>
<p></p>

<h1>3. Le Chateau de Bel Ombre</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/3.-Le-Chataeu-del-Ombre-e1520948908885.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> The restaurant is located 45.6 km from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b> Closed on Sundays </li>
  <li> <b>Approximate Cost for Two:</b>Meal for two may cost approx. INR 6800/-</li>
  <li> <b>Must Try:</b>Black Pepper Crab</li>
  <li> <b>Trip Advisor Rating:</b>4/5</li>
</ul>
<p></p>

<h1>4. Domaine Anna Restaurant</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/10.-domaine-anna-e1520948798350.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> The restaurant is located 45.8 km from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b> 10 am to 2:30 pm – 6:45 pm to 10:30 pm (Tuesday-Sunday) </li>
  <li> <b>Approximate Cost for Two:</b> NA</li>
  <li> <b>Must Try:</b>Fried Rice</li>
  <li> <b>Trip Advisor Rating:</b>4/5</li>
</ul>
<p></p>


<h1>5. Le Fangourin</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/5.-Le-Fangourin-1-e1520949894117.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> he restaurant is located 58.6KM from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b> 9 am to 10 pm </li>
  <li> <b>Approximate Cost for Two:</b>Dishes range between INR 400/- to INR 2000/-</li>
  <li> <b>Must Try:</b>Red Snapper</li>
  <li> <b>Trip Advisor Rating:</b>5/5</li>
</ul>
<p></p>

<h1>6. Rasoi by Vineet
</h1>
<img src="https://blog.thomascook.in/wp-content/uploads/2018/03/6.-rasoi-by-Vineet-e1520948500794.jpg" alt="">
<p></p>
<ul>
  <li><b>Distance from the Airport:</b> The restaurant is located 62.4KM from the Sir Seewoosagur Ramgoolam International Airport in Mauritius.</li>
  <li> <b>How much Time to Spend:</b>1-2 Hours</li>
  <li> <b>Operating Hours:</b> 24 hours but call ahead just to confirm </li>
  <li> <b>Approximate Cost for Two:</b>an Average meal for two may cost Between INR 1600/- to INR 6500/-.</li>
  <li> <b>Must Try:</b>Any Indian Curry and The Tasting Menu</li>
  <li> <b>Trip Advisor Rating:</b>5/5</li>
</ul>
<p></p>
{% endblock %}

Website/homepage/templates/homepage/blog/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
   <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body class="body">
    <header class="mainHeader">
      <!-- <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnntfx4WLnKK8u5-USgIlZzWkRchjvtX5k7FomlwOx200dMch3" alt="" width="50px" height="50px" align="center"> -->
      <nav>
        <ul>
          <li>
            <a href="{% url 'home' %}">Home</a>
          </li>
          <li>
            <a href="{% url 'homepage:aboutus' %}">About Us</a>
          </li>
          <li>
            <a href="#">Contact Us</a>
          </li>
        </ul>
      </nav>

    </header>
{% block body_block %}
    <div class="mainContent">
      <div class="content">
        <article class="topcontent">
          <header>
            <h2>
              <a href="{% url 'homepage:first' %}" class="First post">Why Every Adventure Junkie Needs To Experience Thailand Adventures</a>
            </h2>
          </header>
<footer>
  <p class="post-info">Monday, April 9, 2018</p>
</footer>
<content>
<p><h5>Thailand is enormous and diverse along with the large selection of travel as well as holiday options. Thailand has held a very special place in tourist’s heart. Resorts in coast <a href="{% url 'homepage:first' %}">Read More</a></h5></p>
</content>
        </article>

        <article class="midcontent">
          <header>
            <h2>
              <a href="{% url 'homepage:second' %}" class="Second post">Wildlife Safaris In South Africa – The Perfect Wilderness To Indulge In</a>
            </h2>
          </header>
<footer>
  <p class="post-info">Friday, April 9, 2018</p>
</footer>
<content>
  <p>
  <h5>If Wildlife Safari is on your mind, then you must plan an exciting family or romantic holiday to South Africa and head onto The Kruger National Park. Kruger is among the most exciting destinations in Africa, rivalled only by national reserves in Tanzania. The park is a historic and legendary part of South African history and the best place to enjoy Wildlife Safaris in South Africa. You get to enjoy panoramic views, thrilling wildlife experiences and the cast <a href="{% url 'homepage:second' %}">Read More</a>
  </h5>
  </p>
</content>
        </article>
        <article class="midcontent2">
          <header>
            <h2>
              <a href="{% url 'homepage:third' %}" class="Third post">Things To Do In Europe – 7 Once In A Lifetime Experiences</a>
            </h2>
          </header>
        <footer>
        <p class="post-info">Monday, April 9, 2018</p>
        </footer>
        <content>
          <p>
            <h5>Be it catching a glimpse of the startling Eiffel Tower, having a scrumptious brunch in London, shopping your heart out in Paris, or sipping a perfect cocktail on the lands of Vienna – there isn’t a thing you do in Europe that does not <a href="{% url 'homepage:third' %}">Read More</a>
            </h5>
          </p>
        </content>
        </article>
        <article class="bottomcontent">
          <header>
            <h2>
              <a href="{% url 'homepage:fourth' %}" class="Fourth post">Top 6 Restaurants For The Best Mauritius Food</a>
            </h2>
          </header>
  <footer>
  <p class="post-info">Saturday, March 17, 2018</p>
  </footer>
  <content>
    <p><h5>Mauritius is a breath-taking Island nation with a beautiful landscape with panoramic views that seem like they are out of high definition movie. This quaint nation nestled near the African continent in a very popular year-round tourist destination. It has on offer an abundance of white sandy beaches, turquoise lagoons and bright,
      <a href="{% url 'homepage:fourth' %}">Read More</a></h5>
    </p>
  </content>
        </article>



      </div>

    </div>
<aside class="top-sidebar">
<article class="">
  <h2>Subscribe</h2>
  <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <button type="submit" class="btn btn-primary">Subscribe</button>
</form>

</article>
</aside>

<aside class="middle-sidebar">
<article class="">
  <footer>
  <p class="post-info">SPOTLIGHTS</p>
  </footer>
 <p></p>
<a href="{% url 'homepage:fifth' %}">
<img src="https://blog.thomascook.in/wp-content/uploads/2012/09/20860542330_92df58d1ef_z.jpg" alt="" width="150px">
Indulge Your Need For Speed In Singapore!
</a>
<p></p>
<p><h7>Singapore has a lot to offer for all kinds of travelers. When you plan a trip to this world class destination you can expect your vacation to be full of surprises from beautiful architecture to great food and amazing theme parks!Apart from the obvious tourist attractions, Singapore has something special to offer for sports enthusiasts! If you have a need for speed, then you should
<a href="{% url 'homepage:fifth' %}">Read More</a></h7></p>
</article>
</aside>

<aside class="bottom-sidebar">
  <article class="">
   <p></p>
  <a href="{% url 'homepage:sixth' %}">
  <img src="https://blog.thomascook.in/wp-content/uploads/2018/03/Nanda_Devi-1-1024x683.jpg" alt="" width="150px">
  7 Uniquely Amazing Places You Should Visit For Sure

  </a>
  <p></p>
  <p><h7>One of the most romantic hill stations in India, Nainital is  <a href="{% url 'homepage:sixth' %}">Read More</a></h7></p>
  </aside >
  {% endblock %}
<footer class="mainFooter">
  <p>Copyright &copy;2013 <a href="#" title="tours">tours.cor</a>
  </p>
</footer>
  </body>
</html>